import type { OpenApiDocument, OpenApiOperation } from "./openapi.js";

const escape = (value: unknown): string => String(value).replace(/[&<>"']/g, (character) => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
})[character]!);

export const apiDocsCss = `
:root{color-scheme:light dark;font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace;font-size:14px;line-height:1.6;background:#faf9f6;color:#24231f}
*{box-sizing:border-box}body{margin:0}a{color:inherit;text-underline-offset:3px}a:hover{color:#625ac5}a:focus-visible,summary:focus-visible{outline:2px solid currentColor;outline-offset:4px}main{max-width:1080px;margin:0 auto;padding:36px 24px 64px}header{border-bottom:1px solid #c9c6bf;padding-bottom:24px;margin-bottom:30px}nav{display:flex;flex-wrap:wrap;gap:12px 24px}h1{font-size:clamp(24px,5vw,36px);line-height:1.2;font-weight:500;letter-spacing:-1px;margin:28px 0 14px}h2{font-size:18px;font-weight:500;margin:34px 0 14px}h3{font-size:14px;margin:0 0 8px}p{max-width:80ch;margin:10px 0}.muted{color:#6c6961}.start{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border:1px solid #c9c6bf;margin:26px 0}.start>a{display:block;padding:18px;border-right:1px solid #c9c6bf;text-decoration:none}.start>a:last-child{border-right:0}.start strong{display:block;font-weight:500;margin-bottom:7px}.start span{font-size:12px;color:#6c6961}ol,ul{padding-left:22px}li{margin:6px 0}code{font-family:inherit;font-size:0.94em;overflow-wrap:anywhere}pre{padding:16px;border:1px solid #c9c6bf;overflow-x:auto;background:#f1efea;max-width:100%;white-space:pre-wrap;overflow-wrap:anywhere}pre code{font-size:12px}.reference{border-top:1px solid #c9c6bf;margin-top:26px}.group{border-bottom:1px solid #c9c6bf;padding:0 0 12px}.group>summary{font-size:16px;padding:16px 0;cursor:pointer}.endpoint{margin:0 0 8px;padding:0 0 0 18px}.endpoint>summary{cursor:pointer;overflow-wrap:anywhere}.verb{display:inline-block;min-width:58px;font-size:12px;font-weight:600}.endpoint p{font-size:12px;margin-left:58px}.endpoint .route{font-size:12px}.endpoint .auth{font-size:11px;color:#6c6961}.links{display:flex;flex-wrap:wrap;gap:10px 24px;padding:0;list-style:none}footer{margin-top:44px;padding-top:18px;border-top:1px solid #c9c6bf;font-size:12px}.skip{position:absolute;left:24px;top:-100px}.skip:focus{top:8px;background:#faf9f6;padding:8px}.note{border-left:2px solid #8b857b;padding-left:16px}
@media(max-width:620px){main{padding:24px 16px 40px}.start{grid-template-columns:1fr}.start>a{border-right:0;border-bottom:1px solid #c9c6bf}.start>a:last-child{border-bottom:0}nav{gap:8px 18px}.endpoint{padding-left:0}.endpoint p{margin-left:0}.verb{min-width:52px}pre{padding:12px}}
@media(prefers-color-scheme:dark){:root{background:#171715;color:#e7e4dc}.muted,.start span,.endpoint .auth{color:#aaa69c}header,footer,.start,.start>a,.reference,.group,pre{border-color:#4d4b44}pre{background:#20201c}.skip:focus{background:#171715}a:hover{color:#bbb5ff}}
`;

function authLabel(operation: OpenApiOperation): string {
  const auth = operation["x-auth"] as { scheme?: string; ownerOnly?: boolean; requiredBotScopes?: string[] } | undefined;
  return auth?.scheme === "public" ? "public" : auth?.ownerOnly ? "owner signature" : `signed ${auth?.requiredBotScopes?.join(", ") || "request"}`;
}

/** Static, script-free documentation. Descriptions are escaped and never executed. */
export function apiDocsPage(spec: OpenApiDocument): string {
  const rows = Object.entries(spec.paths).flatMap(([path, methods]) => Object.entries(methods).map(([method, operation]) => ({ path, method: method.toUpperCase(), operation })));
  const groups = spec.tags.map((tag) => {
    const entries = rows.filter((row) => row.operation.tags.includes(tag.name));
    return `<details class="group" id="${escape(tag.name.toLowerCase())}"><summary>${escape(tag.name)} <span class="muted">(${entries.length})</span></summary><p class="muted">${escape(tag.description)}</p>${entries.map(({ path, method, operation }) =>
      `<details class="endpoint"><summary><span class="verb">${escape(method)}</span><span class="route">${escape(path)}</span> <span class="auth">${escape(authLabel(operation))}</span></summary><p>${escape(operation.summary)}</p>${operation.description ? `<p class="muted">${escape(operation.description)}</p>` : ""}<p><code>operationId: ${escape(operation.operationId)}</code></p></details>`).join("")}</details>`;
  }).join("");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Juicebox V6 REST API: discover contracts, read projects and indexed activity, prepare plans and relay signed transactions."><title>REST API | Juicebox Center</title><link rel="stylesheet" href="/assets/api.css"></head>
<body><a class="skip" href="#main">Skip to content</a><main id="main"><header><nav aria-label="Primary"><a href="/">Juicebox Center</a><a href="/accounts">Accounts and bots</a><a href="/#agents">MCP</a></nav><h1>Juicebox V6 REST API</h1><p>Discover contracts, read projects and activity, prepare reviewed calls, and relay transactions signed by a wallet.</p><nav aria-label="API resources"><a href="/api/docs/user-journeys">Choose your journey</a><a href="/api/v1/openapi.json">OpenAPI 3.1.2</a><a href="/api/v1/capabilities">Live capabilities</a><a href="/api/docs/api">Full guide</a><a href="/api/docs/ai-guide">Agent guide</a></nav></header>
<section aria-label="Choose a starting point" class="start"><a href="#read"><strong>I need data →</strong><span>Choose canonical chain state or indexed history.</span></a><a href="#write"><strong>I need a transaction →</strong><span>Prepare, review, sign, then reconcile.</span></a><a href="#reference"><strong>I am building an integration →</strong><span>Discover schemas, methods and supported routes.</span></a></section>
<section id="start"><h2>Start with discovery</h2><p>Catalogs are public. Live reads and writes require an enrolled owner or authorized bot to sign each API request. Use <a href="/accounts">Accounts and bots</a> to enroll and manage access.</p><pre><code>curl https://juicebox.center/api/v1/capabilities
curl 'https://juicebox.center/api/v1/catalog/contracts?limit=25'
curl https://juicebox.center/api/v1/catalog/operations</code></pre><p><a href="/api/docs/quickstart">Browser and CLI quickstart</a> / <a href="/api/docs/authentication">Exact request signing</a></p></section>
<section id="read"><h2>Read the source you need</h2><ul><li><strong>Onchain:</strong> resolve a contract, select its deployed ABI, and call a view or pure method at a reported canonical block.</li><li><strong>Bendystraw:</strong> choose mainnet or testnet, request versioned tables, and follow the returned cursor. Indexer pages are not a block-hash snapshot.</li><li><strong>Semantic operations:</strong> use an operation's published input schema for project, hook, revnet, SDK and development questions.</li></ul><p>Project routes require an explicit <code>source=onchain</code> or <code>source=bendystraw</code>. Keep amounts and large integers as decimal strings. Preserve unknown observations and verification limits.</p><ul class="links"><li><a href="/api/v1/catalog/contracts">Contract catalog</a></li><li><a href="/api/v1/catalog/indexer">Indexer catalog</a></li><li><a href="/api/docs/contracts">Contract guide</a></li><li><a href="/api/docs/indexer">Indexer guide</a></li></ul></section>
<section id="write"><h2>Prepare → review → sign → reconcile</h2><ol><li>Create a plan with a named preparation or <code>contract_calls</code>. Sign the API request and include an <code>Idempotency-Key</code>.</li><li>Review the exact chain, destination, calldata, native value, dependencies, evidence, commitment and expiry. Simulate each ready step.</li><li>Have the plan wallet sign the exact transaction. Submit those signed bytes with a fresh owner-signed API request, or a bot request carrying the owner’s exact approval.</li><li>Retrieve the plan with <code>refresh=true</code>. Continue when prerequisites are confirmed; reconcile unknown broadcasts by their existing hash.</li></ol><p class="note">A bot API grant does not authorize spending the owner's funds. Capability discovery reports enabled transports and sponsorship. Multi-chain journeys are not atomic, and a source-chain receipt does not prove bridge settlement.</p><p><a href="/api/docs/transactions">Plans, retries, confirmations and partial journeys</a> / <a href="/api/docs/sessions">Session lifecycle and quotas</a></p></section>
<section id="relayr"><h2>Use prepaid Relayr execution</h2><p>When capabilities enable it, prepare up to four independent calls, review and sign each exact forwarding authorization, then publish once. Create a separate funding plan from the authenticated quote and have the owner review and sign it.</p><p>Check existing funding before paying. Reconcile exact destination execution; a quote or provider status does not establish payment or success. See the <a href="/api/docs/api">full guide</a> and <a href="/api/docs/ai-guide">agent workflow</a>.</p></section>
<section id="wallets"><h2>Use sponsored smart-wallet execution</h2><p>On <a href="/accounts">Accounts</a>, create or bind a supported Safe, prepare a V6 action, review and sign the exact operation, submit once, then check its receipt. The connected wallet currently pays the creation fee; hosted execution uses the configured paymaster. No bot or session is required for fresh owner approval.</p><p>Optional bot permissions require separate owner activation and a verified session guard. Check availability before offering recurring execution.</p><p><a href="/api/v1/smart-accounts/capabilities">Current wallet capabilities</a> / <a href="/api/docs/smart-accounts">Smart-account guide</a> / <a href="/api/docs/execution-operations">Hosting bundlers and paymasters</a></p></section>
<section id="reference"><h2>Endpoint reference</h2><p class="muted">Expand a group, then an endpoint. The OpenAPI document contains exact parameters and schemas; the contract method catalog supplies ABI-specific argument and output schemas.</p><div class="reference">${groups}</div></section>
<section id="errors"><h2>Errors and retries</h2><p>Errors use <code>application/problem+json</code> with <code>code</code>, <code>status</code>, <code>requestId</code> and <code>retryable</code>. Honor <code>Retry-After</code>. For an idempotent retry, preserve the exact request bytes and key while creating a fresh nonce and API signature.</p><p>Transaction retries never authorize different calldata, fees or nonces for a bound plan step. Read the stored transaction hash and reconcile its state first.</p></section>
<footer><nav aria-label="More resources"><a href="/api/v1/openapi.json">Machine-readable API</a><a href="/api/docs/ai-guide">AI agent integration</a><a href="https://github.com/mejango/jbcenter">Source</a><a href="https://github.com/Bananapus/version-6">V6 repositories</a></nav></footer></main></body></html>`;
}
