import type { OpenApiDocument, OpenApiOperation } from "./openapi.js";

const escape = (value: unknown): string => String(value).replace(/[&<>"']/g, (character) => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
})[character]!);

export const apiDocsCss = `
:root{color-scheme:light dark;font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace;font-size:14px;line-height:1.6;background:#faf9f6;color:#24231f}
*{box-sizing:border-box}body{margin:0}a{color:inherit;text-underline-offset:3px}a:hover{color:#625ac5}a:focus-visible,summary:focus-visible{outline:2px solid currentColor;outline-offset:4px}main{max-width:1080px;margin:0 auto;padding:36px 24px 64px}header{border-bottom:1px solid #c9c6bf;padding-bottom:24px;margin-bottom:30px}nav{display:flex;flex-wrap:wrap;gap:12px 24px}h1{font-size:clamp(24px,5vw,36px);line-height:1.2;font-weight:500;letter-spacing:-1px;margin:28px 0 14px}h2{font-size:18px;font-weight:500;margin:34px 0 14px}h3{font-size:14px;margin:0 0 8px}p{max-width:80ch;margin:10px 0}.muted{color:#6c6961}.start{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border:1px solid #c9c6bf;margin:26px 0}.start>a{display:block;padding:18px;border-right:1px solid #c9c6bf;text-decoration:none}.start>a:last-child{border-right:0}.start strong{display:block;font-weight:500;margin-bottom:7px}.start span{font-size:12px;color:#6c6961}ol,ul{padding-left:22px}li{margin:6px 0}code{font-family:inherit;font-size:0.94em;overflow-wrap:anywhere}pre{padding:16px;border:1px solid #c9c6bf;overflow-x:auto;background:#f1efea;max-width:100%;white-space:pre-wrap;overflow-wrap:anywhere}pre code{font-size:12px}.reference{border-top:1px solid #c9c6bf;margin-top:26px}.group{border-bottom:1px solid #c9c6bf;padding:0 0 12px}.group>summary{font-size:16px;padding:16px 0;cursor:pointer}.endpoint{margin:0 0 8px;padding:0 0 0 18px}.endpoint>summary{cursor:pointer;overflow-wrap:anywhere}.verb{display:inline-block;min-width:58px;font-size:12px;font-weight:600}.endpoint p{font-size:12px;margin-left:58px}.endpoint .route{font-size:12px}.endpoint .auth{font-size:11px;color:#6c6961}.links{display:flex;flex-wrap:wrap;gap:10px 24px;padding:0;list-style:none}footer{margin-top:44px;padding-top:18px;border-top:1px solid #c9c6bf;font-size:12px}.skip{position:absolute;left:24px;top:-100px}.skip:focus{top:8px;background:#faf9f6;padding:8px}.note{border-left:2px solid #8b857b;padding-left:16px}dt{font-weight:600;margin-top:18px;scroll-margin-top:18px}dd{margin:4px 0 0;max-width:80ch}
@media(max-width:620px){main{padding:24px 16px 40px}.start{grid-template-columns:1fr}.start>a{border-right:0;border-bottom:1px solid #c9c6bf}.start>a:last-child{border-bottom:0}nav{gap:8px 18px}.endpoint{padding-left:0}.endpoint p{margin-left:0}.verb{min-width:52px}pre{padding:12px}}
@media(prefers-color-scheme:dark){:root{background:#171715;color:#e7e4dc}.muted,.start span,.endpoint .auth{color:#aaa69c}header,footer,.start,.start>a,.reference,.group,pre{border-color:#4d4b44}pre{background:#20201c}.skip:focus{background:#171715}a:hover{color:#bbb5ff}}
`;

function authLabel(operation: OpenApiOperation): string {
  const auth = operation["x-auth"] as { scheme?: string; ownerOnly?: boolean; requiredBotScopes?: string[] } | undefined;
  return auth?.scheme === "public" ? "public" : auth?.ownerOnly ? "owner signature" : `signed ${auth?.requiredBotScopes?.join(", ") || "request"}`;
}

/** Static, script-free documentation. Descriptions are escaped and never executed. */
export function apiDocsPage(spec: OpenApiDocument): string {
  const rows = Object.entries(spec.paths).flatMap(([path, methods]) => Object.entries(methods).map(([method, operation]) => ({ path, method: method.toUpperCase(), operation })));
  const groups = spec.tags.map((tag) => {
    const entries = rows.filter((row) => row.operation.tags.includes(tag.name));
    return `<details class="group" id="${escape(tag.name.toLowerCase())}"><summary>${escape(tag.name)} <span class="muted">(${entries.length})</span></summary><p class="muted">${escape(tag.description)}</p>${entries.map(({ path, method, operation }) =>
      `<details class="endpoint"><summary><span class="verb">${escape(method)}</span><span class="route">${escape(path)}</span> <span class="auth">${escape(authLabel(operation))}</span></summary><p>${escape(operation.summary)}</p>${operation.description ? `<p class="muted">${escape(operation.description)}</p>` : ""}<p><code>operationId: ${escape(operation.operationId)}</code></p></details>`).join("")}</details>`;
  }).join("");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Juicebox V6 API: read projects, prepare transactions, and check their results."><title>REST API | Juicebox Center</title><link rel="stylesheet" href="/assets/api.css"></head>
<body><a class="skip" href="#main">Skip to content</a><main id="main"><header><nav aria-label="Primary"><a href="/">Juicebox Center</a><a href="/accounts">Accounts and bots</a><a href="/#agents">Assistant tools</a></nav><h1>Juicebox V6 REST API</h1><p>Read project data and prepare transactions for wallet approval. Apps use this service through HTTP requests: a <a href="#glossary-api">REST API</a>.</p><nav aria-label="API resources"><a href="/api/docs/user-journeys">Choose your journey</a><a href="/api/v1/openapi.json">OpenAPI 3.1.2</a><a href="/api/v1/capabilities">Live capabilities</a><a href="/api/docs/api">Full guide</a><a href="/api/docs/ai-guide">Agent guide</a><a href="#glossary">Glossary</a></nav></header>
<section aria-label="Choose a starting point" class="start"><a href="#read"><strong>I need data →</strong><span>Read current values or search project history.</span></a><a href="#write"><strong>I need a transaction →</strong><span>Prepare, review, sign, then check the result.</span></a><a href="#reference"><strong>I am building an integration →</strong><span>Find request formats and supported actions.</span></a></section>
<section id="start"><h2>See what is available</h2><p>The lists of contracts and tools are public. Protected reads and changes require a registered owner or authorized bot to sign each API request. A bot is a program with its own key and limited API permissions. Set up access on <a href="/accounts">Accounts and bots</a>.</p><pre><code>curl https://juicebox.center/api/v1/capabilities
curl 'https://juicebox.center/api/v1/catalog/contracts?limit=25'
curl https://juicebox.center/api/v1/catalog/operations</code></pre><p><a href="/api/docs/quickstart">Browser and CLI quickstart</a> / <a href="/api/docs/authentication">Exact request signing</a></p></section>
<section id="read"><h2>Choose a data source</h2><ul><li><strong>Read the blockchain:</strong> find the deployed contract and its <a href="#glossary-abi">interface (ABI)</a>, then call a read-only method. Results identify the verified block they describe.</li><li><strong>Search history:</strong> Bendystraw collects blockchain records into a searchable <a href="#glossary-indexer">index</a>. Choose real funds (<code>mainnet</code>) or test funds (<code>testnet</code>), filter to V6, and use the returned cursor to get the next page. Pages may reflect different blocks.</li><li><strong>Use a named operation:</strong> choose a project or developer task from the operations catalog and follow its required input format, called a schema.</li></ul><p>Project routes require <code>source=onchain</code> or <code>source=bendystraw</code>. Keep amounts and large integers as decimal strings. If a value could not be read, report it as unknown.</p><ul class="links"><li><a href="/api/v1/catalog/contracts">Contract catalog</a></li><li><a href="/api/v1/catalog/indexer">Indexer catalog</a></li><li><a href="/api/docs/contracts">Contract guide</a></li><li><a href="/api/docs/indexer">Indexer guide</a></li></ul></section>
<section id="write"><h2>Prepare → review → sign → check</h2><ol><li>Create a saved set of proposed transactions: a <a href="#glossary-plan">plan</a>. Use a named preparation or <code>contract_calls</code>. Sign the API request and include an <a href="#glossary-idempotency"><code>Idempotency-Key</code></a> so a retry can find the same result.</li><li>Review the exact chain, recipient, encoded instructions (<a href="#glossary-calldata">calldata</a>), native token amount, required earlier steps, block evidence, plan commitment and expiry. Test each ready step with a simulation.</li><li>Have the plan wallet sign the exact transaction. Submit those signed bytes with a fresh owner-signed API request, or a bot request carrying the owner’s exact approval.</li><li>Retrieve the plan with <code>refresh=true</code> to check what happened. Continue only when required earlier steps are confirmed. Check an uncertain submission by its existing transaction hash before retrying.</li></ol><p class="note">API access does not let a bot spend the owner's funds. Check capabilities for supported ways to send transactions and pay network costs. Steps on different chains can succeed or fail separately; confirmation on the sending chain does not prove funds arrived on the receiving chain.</p><p><a href="/api/docs/transactions">Plans, retries, confirmations and partial journeys</a> / <a href="/api/docs/sessions">Session lifecycle and quotas</a></p></section>
<section id="relayr"><h2>Prepay for transactions across chains</h2><p>Relayr can send up to four independent calls when capabilities enable it. Review and sign permission for each exact call, then publish once. Create a separate funding plan from the verified provider quote and have the owner review and sign it.</p><p>Check whether funding already arrived before paying again. Verify each call on its destination chain; a quote or provider status alone does not prove payment or success. See the <a href="/api/docs/api">full guide</a> and <a href="/api/docs/ai-guide">agent workflow</a>.</p></section>
<section id="wallets"><h2>Use a wallet with sponsored network costs</h2><p>A <a href="#glossary-smart-wallet">smart wallet</a> uses a contract to check its owners' approvals. On <a href="/accounts">Accounts</a>, create or connect a supported Safe wallet, prepare a V6 action, review and sign it, submit once, then check its receipt. Your connected wallet pays the network cost to create it. Later supported transactions use a sponsor contract called a <a href="#glossary-paymaster">paymaster</a>.</p><p>You can approve each transaction without a bot. Optional repeat actions need separate owner permission and a verified contract that enforces its limits, called a session guard. Check availability before offering repeat actions.</p><p><a href="/api/v1/smart-accounts/capabilities">Current wallet capabilities</a> / <a href="/api/docs/smart-accounts">Smart-account guide</a> / <a href="/api/docs/execution-operations">Hosting bundlers and paymasters</a></p></section>
<section id="reference"><h2>Endpoint reference</h2><p class="muted">Expand a group, then an endpoint. The OpenAPI document contains exact parameters and schemas; the contract method catalog supplies ABI-specific argument and output schemas.</p><div class="reference">${groups}</div></section>
<section id="errors"><h2>Errors and retries</h2><p>Errors use <code>application/problem+json</code> with <code>code</code>, <code>status</code>, <code>requestId</code> and <code>retryable</code>. Honor <code>Retry-After</code>. To retry the same request, keep its exact bytes and idempotency key. Use a new one-time request identifier (<a href="#glossary-nonce">nonce</a>) and API signature.</p><p>Retrying a plan step does not authorize changes to its instructions, network costs, or transaction nonce. Look up the stored transaction hash and check its state first.</p></section>
<section id="glossary"><h2>Glossary</h2><p>Look up a term here, then return to the step you were following.</p><dl>
<dt id="glossary-project">Project</dt><dd>A set of Juicebox rules, funds, and tokens. Identify it by both its chain ID and project ID.</dd>
<dt id="glossary-token">Project token / cash out</dt><dd>A project token records participation under a project’s rules. Cashing out gives up tokens permanently in exchange for project funds when those rules allow it. Tokens do not automatically give company ownership or a guaranteed return.</dd>
<dt id="glossary-revnet">Revnet</dt><dd>A Juicebox project with token rules scheduled at launch. Operators retain limited powers; see <a href="https://revnet.money/learn">the revnet guide</a>.</dd>
<dt id="glossary-contract">Smart contract</dt><dd>Code stored on a blockchain that runs when called. The code and its current settings determine what a call can do.</dd>
<dt id="glossary-ruleset">Ruleset</dt><dd>A project's rules for a period of time, including how payments create tokens and what can be paid out.</dd>
<dt id="glossary-terminal">Terminal</dt><dd>A contract that accepts and accounts for a project's payments and cash outs.</dd>
<dt id="glossary-hook">Hook</dt><dd>A contract a project calls to add behavior, such as giving a payer a collectible token.</dd>
<dt id="glossary-network">Mainnet / testnet</dt><dd>A network for real funds / a network for testing with test funds. A chain ID identifies the network.</dd>
<dt id="glossary-canonical">Canonical block</dt><dd>A block checked against the chain's current accepted history. A recent block can still be replaced by a chain reorganization.</dd>
<dt id="glossary-api">API / REST</dt><dd>An API lets programs request data or actions from another program. Center's REST API uses HTTP requests to named URLs.</dd>
<dt id="glossary-schema">Schema / audience</dt><dd>A schema defines a request or response’s exact fields and types. The authentication audience identifies the service a signature is intended for.</dd>
<dt id="glossary-rpc">RPC</dt><dd>A format for asking a remote computer to run a method. Ethereum JSON-RPC is used for blockchain reads and simulations here.</dd>
<dt id="glossary-mcp">MCP</dt><dd>Model Context Protocol: a shared format for connecting AI apps to tools and data.</dd>
<dt id="glossary-sdk">SDK</dt><dd>A software development kit: reusable code for building an app.</dd>
<dt id="glossary-abi">ABI</dt><dd>A contract interface that describes its methods, arguments, outputs, and events. Use the interface for the deployed contract you are calling.</dd>
<dt id="glossary-calldata">Calldata</dt><dd>The encoded instructions sent to a contract: which method to run and its arguments.</dd>
<dt id="glossary-indexer">Indexer / cursor</dt><dd>An indexer collects blockchain records so they can be searched. A cursor marks where the next page starts. Indexed data can lag behind the chain.</dd>
<dt id="glossary-metadata">Metadata / URI</dt><dd>Project details such as a name, description, and image. A URI identifies their location, such as an HTTPS or IPFS address.</dd>
<dt id="glossary-ipfs">IPFS / CID / pinning</dt><dd>IPFS is a shared file network. A CID identifies content; pinning keeps a copy available. A CID does not promise someone will keep hosting the file.</dd>
<dt id="glossary-grant">Bot grant / scope</dt><dd>A grant gives one bot time-limited API access. Scopes choose what it can do: read, plan, or relay. These are not wallet spending permissions.</dd>
<dt id="glossary-authority">Authority chain / principal</dt><dd>The authority chain is part of a Center account's identity. A principal is the owner or bot making an API request.</dd>
<dt id="glossary-plan">Plan / commitment</dt><dd>A plan saves proposed transactions and their required earlier steps. Its commitment is a hash that binds the exact plan being reviewed.</dd>
<dt id="glossary-idempotency">Idempotency key</dt><dd>An identifier that lets the service recognize a repeated request. Reuse it with the same bytes when retrying an operation that supports it.</dd>
<dt id="glossary-nonce">Nonce</dt><dd>A value that prevents reuse of a signed request. Each API attempt needs a fresh random nonce. A wallet transaction nonce instead orders that wallet's transactions.</dd>
<dt id="glossary-smart-wallet">Smart wallet / Safe / EOA</dt><dd>A smart wallet uses a contract to check approvals. Safe is one supported kind. An EOA is an account controlled directly by a private key.</dd>
<dt id="glossary-binding">Wallet binding</dt><dd>A verified link between a Center account and a smart wallet. Linking them does not grant a bot permission to spend.</dd>
<dt id="glossary-relay">Relay / bundler</dt><dd>A relay sends already signed transactions. A bundler submits smart-wallet UserOperations to the chain.</dd>
<dt id="glossary-operation">UserOperation / SafeOp</dt><dd>A UserOperation packages a smart-wallet action for submission. SafeOp is the exact approval document its Safe owners sign.</dd>
<dt id="glossary-session">Session / guard</dt><dd>A session is time-limited permission to repeat specified actions. A guard is a contract that enforces its limits. API access alone does not create a session.</dd>
<dt id="glossary-paymaster">Gas / wei / paymaster</dt><dd>Gas measures the work a transaction uses. Wei is the smallest ETH unit: 10¹⁸ wei equals 1 ETH. A paymaster sponsors supported network costs.</dd>
<dt id="glossary-receipt">Receipt</dt><dd>A blockchain record showing that a transaction was included and whether it succeeded or reverted. Check its events and resulting balances for the intended outcome.</dd>
<dt id="glossary-reconcile">Reconcile</dt><dd>Look up an existing submission and compare it with chain evidence to find out what happened before trying again.</dd>
</dl></section>
<footer><nav aria-label="More resources"><a href="/api/v1/openapi.json">Machine-readable API</a><a href="/api/docs/ai-guide">AI agent integration</a><a href="https://github.com/mejango/jbcenter">Source</a><a href="https://github.com/Bananapus/version-6">V6 repositories</a></nav></footer></main></body></html>`;
}
