import { SAFE7579_OWNER_TYPES } from "../smartAccounts/accountExecution.js";
import { array, decimalString, nullable, object, ref, type Schema } from "./schemas.js";

const text = { type: "string" };
const boolean = { type: "boolean" };
const yes = { type: "boolean", const: true };
const no = { type: "boolean", const: false };
const integer = { type: "integer", minimum: 0, maximum: Number.MAX_SAFE_INTEGER };
const chain = { ...integer, minimum: 1 };
const bytes4 = { type: "string", pattern: "^0x[0-9a-fA-F]{8}$" };
const quantity = (bytes = 32): Schema => ({ type: "string", pattern: `^0x(?:0|[1-9a-f][0-9a-f]{0,${bytes * 2 - 1}})$`,
  description: "Canonical lowercase hexadecimal RPC quantity, with no leading zeros." });
const actor = object({ accountId: ref("AccountId"), principalId: ref("PrincipalId") });
const policyData = object({ policy: ref("Address"), initData: ref("HexBytes") });
const operationFields = {
  sender: ref("Address"), nonce: quantity(), factory: ref("Address"), factoryData: ref("HexBytes"), callData: { ...ref("HexBytes"), maxLength: 131074 },
  callGasLimit: quantity(16), verificationGasLimit: quantity(16), preVerificationGas: quantity(), maxFeePerGas: quantity(16), maxPriorityFeePerGas: quantity(16),
  paymaster: ref("Address"), paymasterVerificationGasLimit: quantity(16), paymasterPostOpGasLimit: quantity(16), paymasterData: ref("HexBytes"),
  signature: { type: "string", const: "0x", description: "Public preparations and reads always omit submitted account signature bytes." },
};

export function sessionSchemas(): Record<string, Schema> {
  return {
    SessionCapabilities: object({ durationsDays: { type: "array", const: [7, 30] }, availableActions: array({ type: "string", enum: ["erc20-transfer", "v6-pay", "v6-project-uri"] }),
      configuredChainIds: array(chain, { uniqueItems: true }), requiresVerifiedGuardDeployment: yes, activationReady: boolean,
    }, ["durationsDays", "availableActions", "configuredChainIds", "requiresVerifiedGuardDeployment", "activationReady"], true),
    CompiledSessionPolicy: object({ kind: { type: "string", enum: ["time-frame", "universal-action", "value-limit", "usage-limit", "gas-budget"] },
      policy: ref("SmartContractPin"), configId: ref("Hash"), scope: { type: "string", enum: ["user-operation", "action"] }, actionId: ref("Hash"),
      initData: ref("HexBytes"), decoded: ref("JsonValue") }, ["kind", "policy", "configId", "scope", "initData", "decoded"]),
    LegacySessionTuple: object({ sessionValidator: ref("Address"), sessionValidatorInitData: ref("HexBytes"), salt: ref("Hash"),
      userOpPolicies: array(policyData), erc7739Policies: object({ allowedERC7739Content: { type: "array", maxItems: 0 }, erc1271Policies: { type: "array", maxItems: 0 } }),
      actions: array(object({ actionTargetSelector: bytes4, actionTarget: ref("Address"), actionPolicies: array(policyData) }), { minItems: 1, maxItems: 16 }),
      permitERC4337Paymaster: yes }),
    CompiledSession: object({ schemaVersion: { type: "integer", const: 1 }, stack: { type: "string", const: "legacy-f24dddf-safe7579-f22a194" },
      ownerAccountId: ref("AccountId"), bindingId: ref("Hash"), grantId: ref("ResourceId"), sessionKey: ref("Address"), chainId: chain, wallet: ref("Address"),
      generation: ref("PositiveUint256"), nonce: ref("Hash"), validAfter: ref("UnixSeconds"), validUntil: ref("UnixSeconds"), salt: ref("Hash"),
      policyHash: ref("Hash"), compiledHash: ref("Hash"), permissionId: ref("Hash"), manifestRevision: ref("Hash"), activationEnableNonce: ref("Uint256"),
      reviewedPolicy: { allOf: [ref("ReviewedSessionPolicy"), { type: "object", required: ["gasBudget"] }] },
      smartSessions: ref("SmartContractPin"), sessionValidator: ref("SmartContractPin"), session: ref("LegacySessionTuple"),
      configurations: array(ref("CompiledSessionPolicy"), { maxItems: 64 }) }),
    SessionCounter: object({ policy: ref("Address"), configId: ref("Hash"), name: { ...text, minLength: 1, maxLength: 128 },
      used: ref("Uint256"), limit: ref("Uint256") }),
    SessionAdministrationBaseline: object({ epoch: ref("Uint256"), hash: ref("Hash") }),
    SessionAdministrationObservation: object({ epoch: ref("Uint256"), hash: ref("Hash"),
      lastInitialization: object({ epoch: ref("Uint256"), permissionIds: array(ref("Hash"), { maxItems: 16 }) }) }, ["epoch", "hash"]),
    InstalledSessionObservation: { ...object({ permissionId: ref("Hash"), compiledHash: ref("Hash"), account: ref("Address"), chainId: chain,
      enabled: boolean, enableNonce: ref("Uint256"), configurationHash: ref("Hash"), evidence: ref("BlockEvidence"),
      counters: array(ref("SessionCounter"), { maxItems: 256 }), administration: ref("SessionAdministrationObservation") },
    ["permissionId", "compiledHash", "account", "chainId", "enabled", "enableNonce", "configurationHash", "evidence", "counters"]),
    allOf: [{ if: { properties: { enabled: { const: true } }, required: ["enabled"] },
      then: { required: ["administration"], properties: { administration: { required: ["lastInitialization"] } } } }],
    description: "Enabled observations include complete canonical administration history. Admission requires exactly one initialization after the immutable preparation baseline, containing only this permission; changed administration invalidates the generation." },
    SessionCanonicalObservation: object({ installed: ref("InstalledSessionObservation"), observedAt: ref("UnixMilliseconds"), finalized: boolean, proofHash: ref("Hash") }),
    SessionOwnerPlanApproval: { ...object({ kind: { type: "string", enum: ["activation", "revocation"] }, accountId: ref("AccountId"), sessionId: ref("ResourceId"),
      policyHash: ref("Hash"), compiledHash: ref("Hash"), planId: ref("ResourceId"), planCommitment: ref("Hash"), digest: ref("Hash"),
      issuedAt: ref("UnixSeconds"), expiresAt: ref("UnixSeconds") }), description: "Stored server-verified consent for the owner's exact lifecycle-plan request. It is not an HTTP proof submission or an onchain Safe signature." },
    SessionInvalidation: object({ reason: { type: "string", enum: ["reorg", "configuration-changed", "counter-reset", "grant-inactive", "binding-unlinked", "verification-unavailable"] },
      priorProofHash: nullable(ref("Hash")), observedAt: ref("UnixMilliseconds") }),
    SessionState: { type: "string", enum: ["prepared", "installing", "active", "revoking", "revoked", "expired", "stale"] },
    StoredSession: { ...object({ id: ref("ResourceId"), actor, compiled: ref("CompiledSession"), preparedAdministration: ref("SessionAdministrationBaseline"),
      allocationGroups: array(ref("ReviewedSessionAllocationGroup"), { maxItems: 16 }),
      allocationManifestHash: ref("Hash"), createdAt: ref("UnixMilliseconds"), updatedAt: ref("UnixMilliseconds"), revision: integer, state: ref("SessionState"),
      activation: ref("SessionOwnerPlanApproval"), revocation: ref("SessionOwnerPlanApproval"), observation: ref("SessionCanonicalObservation"),
      invalidation: ref("SessionInvalidation"), reservationsReleased: boolean,
      supersededApprovals: array(object({ approval: ref("SessionOwnerPlanApproval"), supersededAt: ref("UnixMilliseconds") }), { maxItems: 32 }),
    }, ["id", "actor", "compiled", "preparedAdministration", "allocationGroups", "allocationManifestHash", "createdAt", "updatedAt", "revision", "state", "reservationsReleased"]),
    description: "Immutable approved policy plus revisioned lifecycle evidence. Only active with fresh canonical proof permits bot execution. Expiry, API revocation and unlinking do not release wallet reservations; finalized disabled state with an advanced enable nonce is required." },
    SessionPreparationInput: { allOf: [ref("SessionReviewInput"), { type: "object", required: ["gasBudget"] }],
      description: "Compile and store an exact seven- or thirty-day session. Requires a reviewed gas-only sponsor and complete runtime/module verification. Preparation does not install authority." },
    SessionPage: object({ items: array(ref("StoredSession"), { maxItems: 100 }), nextCursor: ref("ResourceId") }, ["items"]),
    SessionPlanInput: object({ compiledHash: ref("Hash") }),
    SessionPlanResult: object({ session: ref("StoredSession"), plan: ref("Plan"), installationConfirmed: { ...boolean,
      description: "New lifecycle plans return false. An idempotent replay of the admitted plan returns true when the stored session is already active; the response does not perform another installation or refresh chain evidence." } }),
    SessionQuota: { ...object({ sessionId: ref("ResourceId"), state: ref("SessionState"), allocationManifestHash: ref("Hash"),
      approvedGroups: array(ref("ReviewedSessionAllocationGroup")), localAllocations: array(ref("ReviewedSessionAllocation")),
      counters: nullable(array(ref("SessionCounter"))), observation: nullable(ref("SessionCanonicalObservation")), reservationsReleased: boolean,
      executionAuthority: no, balanceSource: { type: "string", const: "onchain-only" }, atomicAcrossChains: no }),
      description: "Approved allocations and observed policy counters. This is not a spendable database balance or a cross-chain atomic budget." },
    UserOperationSessionBinding: object({ id: ref("ResourceId"), policyHash: ref("Hash"), compiledHash: ref("Hash"), generation: ref("PositiveUint256"),
      grantId: ref("ResourceId"), permissionId: ref("Hash"), sessionKey: ref("Address"), observationHash: ref("Hash") }),
    UserOperationCapabilities: object({ transport: { type: "string", const: "eip4337-user-operation" }, version: { type: "string", const: "0.7" },
      providers: array(object({ chainId: chain, providerId: text, entryPoint: ref("Address"), version: { type: "string", const: "0.7" }, paymasterConfigured: boolean })),
      preparation: boolean, relay: boolean, privateKeysStored: no, automaticResubmission: no,
      sessionMaximumCallsPerOperation: { type: "integer", const: 1 }, ownerMaximumCallsPerOperation: { type: "integer", const: 16 },
      freshOwnerApprovalOutsideSession: yes, activationRequirements: array(text) }),
    PrepareUserOperation: { ...object({ planId: ref("ResourceId"), stepIndexes: array({ type: "integer", minimum: 0, maximum: 31 }, { minItems: 1, maxItems: 16, uniqueItems: true }),
      sessionId: ref("ResourceId") }, ["planId", "stepIndexes"]),
      allOf: [{ if: { required: ["sessionId"] }, then: { properties: { stepIndexes: { maxItems: 1 } } } }],
      description: "Use the creating principal of a durable smart-account plan. Indices must increase in original order. Omit `sessionId` for current Safe-owner threshold signing; a bound bot supplies `sessionId` for one approved action." },
    UserOperationV07: { ...object(operationFields, ["sender", "nonce", "callData", "callGasLimit", "verificationGasLimit", "preVerificationGas", "maxFeePerGas", "maxPriorityFeePerGas", "signature"]),
      dependentRequired: { factory: ["factoryData"], factoryData: ["factory"], paymaster: ["paymasterVerificationGasLimit", "paymasterPostOpGasLimit", "paymasterData"],
        paymasterVerificationGasLimit: ["paymaster"], paymasterPostOpGasLimit: ["paymaster"], paymasterData: ["paymaster"] },
      description: "Unpacked EntryPoint v0.7 operation. RPC integers are hexadecimal quantities; reviewed policy amounts use decimal strings. No v0.8 or EIP-7702 extensions." },
    SafeOwnerUserOperationSigning: object({ scheme: { type: "string", const: "eip712-safe7579-owner" }, digest: ref("Hash"),
      validAfter: decimalString(281474976710655), validUntil: decimalString(281474976710655), typedData: object({
        domain: object({ chainId: chain, verifyingContract: ref("Address") }), types: { type: "object", const: SAFE7579_OWNER_TYPES },
        primaryType: { type: "string", const: "SafeOp" }, message: object({ safe: ref("Address"), nonce: ref("Uint256"), initCode: ref("HexBytes"), callData: ref("HexBytes"),
          verificationGasLimit: ref("Uint256"), callGasLimit: ref("Uint256"), preVerificationGas: ref("Uint256"), maxPriorityFeePerGas: ref("Uint256"), maxFeePerGas: ref("Uint256"),
          paymasterAndData: ref("HexBytes"), validAfter: decimalString(281474976710655), validUntil: decimalString(281474976710655), entryPoint: ref("Address") }) }) }),
    SessionUserOperationSigning: object({ scheme: { type: "string", const: "eip191-legacy-ownable-user-operation" }, operationHash: ref("Hash"), digest: ref("Hash"),
      message: object({ raw: ref("Hash") }), permissionId: ref("Hash"), signaturePrefix: { type: "string", pattern: "^0x00[0-9a-fA-F]{64}$" } }),
    SubmitUserOperation: object({ signature: { type: "string", pattern: "^0x(?:[0-9a-fA-F]{2}){1,16384}$",
      description: "Complete account signature envelope for the exact prepared operation. Owner mode wraps sorted threshold SafeOp signatures and validity bounds. Session mode wraps the installed bot key's EIP-191 signature using the returned permission prefix." } }),
    UserOperationObservation: object({ state: { type: "string", enum: ["pending", "unknown", "confirming", "confirmed", "reverted"] }, operationHash: ref("Hash"),
      transactionHash: ref("Hash"), receipt: ref("TransactionReceipt"), scopedLogs: array(ref("JsonValue")), semantic: ref("SemanticResult"), reason: text }, ["state", "operationHash"]),
    UserOperation: object({ id: ref("ResourceId"), planId: ref("ResourceId"), planCommitment: ref("Hash"),
      stepIndexes: array({ type: "integer", minimum: 0, maximum: 31 }, { minItems: 1, maxItems: 16, uniqueItems: true }), chainId: chain, entryPoint: ref("Address"),
      operation: ref("UserOperationV07"), operationHash: ref("Hash"), commitment: ref("Hash"), accountBindingId: ref("Hash"), accountStateHash: ref("Hash"),
      session: ref("UserOperationSessionBinding"), gasPolicyId: text, providerId: text, createdAt: ref("UnixMilliseconds"), expiresAt: ref("UnixMilliseconds"), revision: integer,
      state: { type: "string", enum: ["prepared", "submitting", "submission_unknown", "pending", "unknown", "confirming", "confirmed", "reverted"] },
      signing: { oneOf: [ref("SafeOwnerUserOperationSigning"), ref("SessionUserOperationSigning")] },
      submission: object({ commitment: ref("Hash"), startedAt: ref("UnixMilliseconds") }), observation: ref("UserOperationObservation"),
    }, ["id", "planId", "planCommitment", "stepIndexes", "chainId", "entryPoint", "operation", "operationHash", "commitment", "accountBindingId", "accountStateHash", "gasPolicyId", "providerId", "createdAt", "expiresAt", "revision", "state", "signing"]),
  };
}
