import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { buildSchema, parse, validate } from 'graphql';
import { describe, expect, it } from 'vitest';
import { BENDYSTRAW_OPERATIONS } from '../../src/adapters/bendystraw.js';

// Full schema generated by the actual local V6 Ponder schema builder. Keeping the
// fixture makes query/argument/field compatibility checks reproducible in an isolated repo.
const sdl = readFileSync(new URL('./fixtures/bendystraw-v6.graphql', import.meta.url), 'utf8');
const provenance = JSON.parse(
  readFileSync(new URL('./fixtures/bendystraw-v6.provenance.json', import.meta.url), 'utf8'),
) as { fixtureSha256: string };
const schema = buildSchema(sdl);

describe('fixed operations against the generated Bendystraw V6 schema', () => {
  it('uses the exact schema snapshot recorded in the provenance manifest', () => {
    expect(createHash('sha256').update(sdl).digest('hex')).toBe(provenance.fixtureSha256);
  });

  for (const [name, query] of Object.entries(BENDYSTRAW_OPERATIONS)) {
    it(`${name}: fields, variable types, filters, relations and pagination exist in the real schema`, () => {
      expect(validate(schema, parse(query)).map((error) => error.message)).toEqual([]);
    });
  }
});
